    image: node:latest

    stages:
      - build
      - test
      
    install_dependencies:
      stage: build
      script:
        - npm install --prefix frontend/afk_frontend

    testing:
      stage: test
      script: npm test --prefix frontend/afk_frontend