    image: node:latest

    stages:
      - build
      - test

    cache:
      paths:
        - frontend/afk_frontend/node_modules/
        
    install_dependencies:
      stage: build
      script:
        - npm install --prefix frontend/afk_frontend/.
      artifacts:
        paths:
          - node_modules/

    testing:
      stage: test
      script: npm test --prefix frontend/afk_frontend
