    image: node:latest

    stages:
      - build
      - test
      
    install_dependencies:
      stage: build
      script:
        - npm install
      artifacts:
        paths:
          - node_modules/

    testing:
      stage: test
      script: npm test --prefix frontend/afk_frontend